
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          #- not_null
          #- accepted_values:                           se comenta para usar el my_second_dbt_model
          #    values: ['accepted', denied]
              #values: [1, 2]
              #quote: false
  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique

          - relationships:
              to: ref('my_first_dbt_model')
              field: id

  - name: snowflake_customer_purchases
    description: "the total purchases for each customer in snowflake sample data"
    columns:
      - name: c_custkey
        tests: 
          - unique
          - not_null

  - name: cumulative_orders_by_date

  - name: incremental_time


## buscar data de una tabla
sources:
  - name: sample
    database: snowflake_sample_data   # Tell dbt to look for the source in the "raw" database
    schema: tpch_sf1
    tables:
      - name: customer
        columns:
          - name: c_custkey
            tests:
              - unique
              - not_null
      - name: orders
## buscar data de una tabla
  - name: sample2
    database: snowflake_sample_data
    schema: tpch_sf100
    tables:
      - name: customer